### возвращает список сотрудников по департаменту.
GET http://localhost:8080/department/employees?id=1
### возвращает сумму зарплат по департаменту.
GET http://localhost:8080/department/salary/sum?id=1
### возвращает максимальную зарплату по департаменту.
GET http://localhost:8080/department/salary/max?id=1
### возвращает минимальную зарплату по департаменту.
GET http://localhost:8080/department/salary/min?id=1
### возвращает сотрудников сгруппированых по отделам в виде Map<Integer,List<Employees>> где ключ - это номер отдела, а значение - список сотрудников данного отдела.
GET http://localhost:8080/department/employees/grouped