### Получить всех сотрудников
GET http://localhost:8080/employees
### Создать сотрудника
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Test",
  "department": 1,
  "salary": 1000
}
### Создать сотрудника 2
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "testdf",
  "lastName": "Test",
  "department": 2,
  "salary": 3000
}
### Создать сотрудника 3
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Testld",
  "lastName": "Testsd",
  "department": 3,
  "salary": 2000
}
### Создать сотрудника 4
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Testfdfsd",
  "lastName": "Testfsdfsd",
  "department": 4,
  "salary": 4000
}

### Получить сумму заплат по сотрудникам
GET http://localhost:8080/employees/salary/sum

### Получить сотрудника с минимальной заработной платой
GET http://localhost:8080/employees/salary/min

### Получить сотрудника с максимальной заработной платой
GET http://localhost:8080/employees/salary/max

### Получение всех сотрудников, зарплата которых больше средней зарплаты
GET http://localhost:8080/employees/high-salary